if vim.g.vscode then
    require 'metagigachad.vscode'
else
    require 'metagigachad.options'
    require 'metagigachad.packer'
    require 'compiled.packer_compiled'
    require 'metagigachad.colorscheme'
    require 'metagigachad.bufferline'
    require 'metagigachad.cmp'
    require 'metagigachad.lsp.lsp'
    require 'metagigachad.null-ls'
    require 'metagigachad.lsp.inlay_hints'
    require 'metagigachad.treesitter'
    require 'metagigachad.comment'
    require 'metagigachad.rust-tools'
    require 'metagigachad.orgmode'
    require 'metagigachad.latex'
    require 'metagigachad.git'
    require 'metagigachad.lualine'
    require 'metagigachad.keymaps'
    require 'metagigachad.telescope'
end
